name: TlrmLsdm
channels:
  - defaults
dependencies:
  - absl-py==2.1.0
  - accelerate==0.26.1
  - aiohttp==3.9.3
  - aiosignal==1.3.1
  - antlr4-python3-runtime==4.9.3
  - appdirs==1.4.4
  - async-timeout==4.0.3
  - attrs==23.2.0
  - blobfile==2.1.1
  - cachetools==5.3.3
  - certifi==2023.11.17
  - charset-normalizer==3.3.2
  - click==8.1.7
  - contourpy==1.1.1
  - cycler==0.12.1
  - datasets==2.16.1
  - diffusers==0.15.0
  - dill==0.3.7
  - docker-pycreds==0.4.0
  - einops==0.6.0
  - filelock==3.13.1
  - fonttools==4.47.0
  - frozenlist==1.4.1
  - fsspec==2023.10.0
  - gitdb==4.0.11
  - GitPython==3.1.40
  - google-auth==2.29.0
  - google-auth-oauthlib==0.4.6
  - grpcio==1.64.0
  - huggingface-hub==0.20.3
  - idna==3.4
  - importlib-metadata==7.0.1
  - importlib-resources==6.1.1
  - Jinja2==3.1.2
  - kiwisolver==1.4.5
  - lightning-utilities==0.11.2
  - lpips==0.1.4
  - lxml==4.9.3
  - Markdown==3.6
  - MarkupSafe==2.1.3
  - matplotlib==3.7.4
  - mpi4py==3.1.4
  - mpmath==1.3.0
  - multidict==6.0.4
  - multiprocess==0.70.15
  - networkx==3.1
  - numpy==1.24.4
  - nvidia-cublas-cu12==12.1.3.1
  - nvidia-cuda-cupti-cu12==12.1.105
  - nvidia-cuda-nvrtc-cu12==12.1.105
  - nvidia-cuda-runtime-cu12==12.1.105
  - nvidia-cudnn-cu12==8.9.2.26
  - nvidia-cufft-cu12==11.0.2.54
  - nvidia-curand-cu12==10.3.2.106
  - nvidia-cusolver-cu12==11.4.5.107
  - nvidia-cusparse-cu12==12.1.0.106
  - nvidia-nccl-cu12==2.18.1
  - nvidia-nvjitlink-cu12==12.3.101
  - nvidia-nvtx-cu12==12.1.105
  - oauthlib==3.2.2
  - omegaconf==2.3.0
  - opencv-python==4.9.0.80
  - packaging==23.2
  - pandas==2.0.3
  - Pillow==10.1.0
  - protobuf==4.25.1
  - psutil==5.9.7
  - pyarrow==15.0.0
  - pyarrow-hotfix==0.6
  - pyasn1==0.6.0
  - pyasn1_modules==0.4.0
  - pycryptodomex==3.19.0
  - pyparsing==3.1.1
  - python-dateutil==2.8.2
  - pytorch-fid==0.3.0
  - pytorch-lightning==1.9.3
  - pytz==2023.4
  - PyYAML==5.4.1
  - regex==2023.12.25
  - requests==2.31.0
  - requests-oauthlib==2.0.0
  - rsa==4.9
  - safetensors==0.4.2
  - scipy==1.10.1
  - sentry-sdk==1.39.1
  - setproctitle==1.3.3
  - six==1.16.0
  - smmap==5.0.1
  - sympy==1.12
  - tensorboard==2.12.0
  - tensorboard-data-server==0.7.2
  - tensorboard-plugin-wit==1.8.1
  - tokenizers==0.15.1
  - torch==2.1.1
  - torchaudio==2.1.1
  - torchmetrics==1.4.0.post0
  - torchsummary==1.5.1
  - torchvision==0.16.1
  - tqdm==4.66.1
  - transformers==4.37.2
  - triton==2.1.0
  - typing_extensions==4.8.0
  - tzdata==2023.4
  - urllib3==2.1.0
  - wandb==0.16.1
  - Werkzeug==3.0.3
  - xformers==0.0.24
  - xxhash==3.4.1
  - yarl==1.9.4
  - zipp==3.17.0
